name: Conditional Workflow

on: [push]

jobs:
  hello-world:
   if: github.repository == 'Devanshukoli/CodeWars'
   runs-on: ubuntu-latest
   steps:
    - name: "Hello Wrold"
      run: echo "hello World!"
  goodbye-moon:
   runs-on: ubuntu-latest
   steps:
    - name: "Goodbye Moon"
      run: echo "Goodbye Moon!"